/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletsImport } from './routes/wallets'
import { Route as TransactionsImport } from './routes/transactions'
import { Route as SettingsImport } from './routes/settings'
import { Route as ReportsImport } from './routes/reports'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as InvestmentsImport } from './routes/investments'
import { Route as GoalsImport } from './routes/goals'
import { Route as CreditCardsImport } from './routes/credit-cards'
import { Route as CategoriesImport } from './routes/categories'
import { Route as BudgetImport } from './routes/budget'
import { Route as IndexImport } from './routes/index'
import { Route as InvitesAcceptImport } from './routes/invites.accept'
import { Route as ApiRegisterImport } from './routes/api/register'
import { Route as ApiWalletsIndexImport } from './routes/api/wallets/index'
import { Route as ApiTransactionsIndexImport } from './routes/api/transactions/index'
import { Route as ApiRatesIndexImport } from './routes/api/rates/index'
import { Route as ApiNotificationsIndexImport } from './routes/api/notifications/index'
import { Route as ApiInvitesIndexImport } from './routes/api/invites/index'
import { Route as ApiInvestmentTransactionsIndexImport } from './routes/api/investment-transactions/index'
import { Route as ApiCreditCardsIndexImport } from './routes/api/credit-cards/index'
import { Route as ApiCreditCardInvoicesIndexImport } from './routes/api/credit-card-invoices/index'
import { Route as ApiCategoriesIndexImport } from './routes/api/categories/index'
import { Route as ApiBudgetsIndexImport } from './routes/api/budgets/index'
import { Route as ApiBudgetCopyIndexImport } from './routes/api/budget-copy/index'
import { Route as ApiAssetsIndexImport } from './routes/api/assets/index'
import { Route as ApiAlertsIndexImport } from './routes/api/alerts/index'
import { Route as ApiWalletsIdImport } from './routes/api/wallets/$id'
import { Route as ApiTransactionsIdImport } from './routes/api/transactions/$id'
import { Route as ApiSettingsPreferencesImport } from './routes/api/settings/preferences'
import { Route as ApiNotificationsIdImport } from './routes/api/notifications/$id'
import { Route as ApiInvitesAcceptImport } from './routes/api/invites/accept'
import { Route as ApiInvestmentsProfitabilityImport } from './routes/api/investments/profitability'
import { Route as ApiInvestmentsExportImport } from './routes/api/investments/export'
import { Route as ApiInvestmentTransactionsIdImport } from './routes/api/investment-transactions/$id'
import { Route as ApiCreditCardsIdImport } from './routes/api/credit-cards/$id'
import { Route as ApiCreditCardInvoicesPayImport } from './routes/api/credit-card-invoices/pay'
import { Route as ApiCategoriesIdImport } from './routes/api/categories/$id'
import { Route as ApiBudgetsIdImport } from './routes/api/budgets/$id'
import { Route as ApiBrokerageNotesParseImport } from './routes/api/brokerage-notes/parse'
import { Route as ApiBrokerageNotesImportImport } from './routes/api/brokerage-notes/import'
import { Route as ApiAuthSplatImport } from './routes/api/auth/$'
import { Route as ApiAssetsIdImport } from './routes/api/assets/$id'
import { Route as ApiAlertsIdImport } from './routes/api/alerts/$id'

// Create/Update Routes

const WalletsRoute = WalletsImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsRoute = TransactionsImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ReportsRoute = ReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InvestmentsRoute = InvestmentsImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRoute,
} as any)

const GoalsRoute = GoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRoute,
} as any)

const CreditCardsRoute = CreditCardsImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesRoute = CategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any)

const BudgetRoute = BudgetImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InvitesAcceptRoute = InvitesAcceptImport.update({
  id: '/invites/accept',
  path: '/invites/accept',
  getParentRoute: () => rootRoute,
} as any)

const ApiRegisterRoute = ApiRegisterImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRoute,
} as any)

const ApiWalletsIndexRoute = ApiWalletsIndexImport.update({
  id: '/api/wallets/',
  path: '/api/wallets/',
  getParentRoute: () => rootRoute,
} as any)

const ApiTransactionsIndexRoute = ApiTransactionsIndexImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const ApiRatesIndexRoute = ApiRatesIndexImport.update({
  id: '/api/rates/',
  path: '/api/rates/',
  getParentRoute: () => rootRoute,
} as any)

const ApiNotificationsIndexRoute = ApiNotificationsIndexImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvitesIndexRoute = ApiInvitesIndexImport.update({
  id: '/api/invites/',
  path: '/api/invites/',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvestmentTransactionsIndexRoute =
  ApiInvestmentTransactionsIndexImport.update({
    id: '/api/investment-transactions/',
    path: '/api/investment-transactions/',
    getParentRoute: () => rootRoute,
  } as any)

const ApiCreditCardsIndexRoute = ApiCreditCardsIndexImport.update({
  id: '/api/credit-cards/',
  path: '/api/credit-cards/',
  getParentRoute: () => rootRoute,
} as any)

const ApiCreditCardInvoicesIndexRoute = ApiCreditCardInvoicesIndexImport.update(
  {
    id: '/api/credit-card-invoices/',
    path: '/api/credit-card-invoices/',
    getParentRoute: () => rootRoute,
  } as any,
)

const ApiCategoriesIndexRoute = ApiCategoriesIndexImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRoute,
} as any)

const ApiBudgetsIndexRoute = ApiBudgetsIndexImport.update({
  id: '/api/budgets/',
  path: '/api/budgets/',
  getParentRoute: () => rootRoute,
} as any)

const ApiBudgetCopyIndexRoute = ApiBudgetCopyIndexImport.update({
  id: '/api/budget-copy/',
  path: '/api/budget-copy/',
  getParentRoute: () => rootRoute,
} as any)

const ApiAssetsIndexRoute = ApiAssetsIndexImport.update({
  id: '/api/assets/',
  path: '/api/assets/',
  getParentRoute: () => rootRoute,
} as any)

const ApiAlertsIndexRoute = ApiAlertsIndexImport.update({
  id: '/api/alerts/',
  path: '/api/alerts/',
  getParentRoute: () => rootRoute,
} as any)

const ApiWalletsIdRoute = ApiWalletsIdImport.update({
  id: '/api/wallets/$id',
  path: '/api/wallets/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiTransactionsIdRoute = ApiTransactionsIdImport.update({
  id: '/api/transactions/$id',
  path: '/api/transactions/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiSettingsPreferencesRoute = ApiSettingsPreferencesImport.update({
  id: '/api/settings/preferences',
  path: '/api/settings/preferences',
  getParentRoute: () => rootRoute,
} as any)

const ApiNotificationsIdRoute = ApiNotificationsIdImport.update({
  id: '/api/notifications/$id',
  path: '/api/notifications/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvitesAcceptRoute = ApiInvitesAcceptImport.update({
  id: '/api/invites/accept',
  path: '/api/invites/accept',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvestmentsProfitabilityRoute =
  ApiInvestmentsProfitabilityImport.update({
    id: '/api/investments/profitability',
    path: '/api/investments/profitability',
    getParentRoute: () => rootRoute,
  } as any)

const ApiInvestmentsExportRoute = ApiInvestmentsExportImport.update({
  id: '/api/investments/export',
  path: '/api/investments/export',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvestmentTransactionsIdRoute =
  ApiInvestmentTransactionsIdImport.update({
    id: '/api/investment-transactions/$id',
    path: '/api/investment-transactions/$id',
    getParentRoute: () => rootRoute,
  } as any)

const ApiCreditCardsIdRoute = ApiCreditCardsIdImport.update({
  id: '/api/credit-cards/$id',
  path: '/api/credit-cards/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiCreditCardInvoicesPayRoute = ApiCreditCardInvoicesPayImport.update({
  id: '/api/credit-card-invoices/pay',
  path: '/api/credit-card-invoices/pay',
  getParentRoute: () => rootRoute,
} as any)

const ApiCategoriesIdRoute = ApiCategoriesIdImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiBudgetsIdRoute = ApiBudgetsIdImport.update({
  id: '/api/budgets/$id',
  path: '/api/budgets/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiBrokerageNotesParseRoute = ApiBrokerageNotesParseImport.update({
  id: '/api/brokerage-notes/parse',
  path: '/api/brokerage-notes/parse',
  getParentRoute: () => rootRoute,
} as any)

const ApiBrokerageNotesImportRoute = ApiBrokerageNotesImportImport.update({
  id: '/api/brokerage-notes/import',
  path: '/api/brokerage-notes/import',
  getParentRoute: () => rootRoute,
} as any)

const ApiAuthSplatRoute = ApiAuthSplatImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRoute,
} as any)

const ApiAssetsIdRoute = ApiAssetsIdImport.update({
  id: '/api/assets/$id',
  path: '/api/assets/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiAlertsIdRoute = ApiAlertsIdImport.update({
  id: '/api/alerts/$id',
  path: '/api/alerts/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetImport
      parentRoute: typeof rootRoute
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesImport
      parentRoute: typeof rootRoute
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsImport
      parentRoute: typeof rootRoute
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsImport
      parentRoute: typeof rootRoute
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsImport
      parentRoute: typeof rootRoute
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsImport
      parentRoute: typeof rootRoute
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterImport
      parentRoute: typeof rootRoute
    }
    '/invites/accept': {
      id: '/invites/accept'
      path: '/invites/accept'
      fullPath: '/invites/accept'
      preLoaderRoute: typeof InvitesAcceptImport
      parentRoute: typeof rootRoute
    }
    '/api/alerts/$id': {
      id: '/api/alerts/$id'
      path: '/api/alerts/$id'
      fullPath: '/api/alerts/$id'
      preLoaderRoute: typeof ApiAlertsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/api/assets/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatImport
      parentRoute: typeof rootRoute
    }
    '/api/brokerage-notes/import': {
      id: '/api/brokerage-notes/import'
      path: '/api/brokerage-notes/import'
      fullPath: '/api/brokerage-notes/import'
      preLoaderRoute: typeof ApiBrokerageNotesImportImport
      parentRoute: typeof rootRoute
    }
    '/api/brokerage-notes/parse': {
      id: '/api/brokerage-notes/parse'
      path: '/api/brokerage-notes/parse'
      fullPath: '/api/brokerage-notes/parse'
      preLoaderRoute: typeof ApiBrokerageNotesParseImport
      parentRoute: typeof rootRoute
    }
    '/api/budgets/$id': {
      id: '/api/budgets/$id'
      path: '/api/budgets/$id'
      fullPath: '/api/budgets/$id'
      preLoaderRoute: typeof ApiBudgetsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-card-invoices/pay': {
      id: '/api/credit-card-invoices/pay'
      path: '/api/credit-card-invoices/pay'
      fullPath: '/api/credit-card-invoices/pay'
      preLoaderRoute: typeof ApiCreditCardInvoicesPayImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-cards/$id': {
      id: '/api/credit-cards/$id'
      path: '/api/credit-cards/$id'
      fullPath: '/api/credit-cards/$id'
      preLoaderRoute: typeof ApiCreditCardsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/investment-transactions/$id': {
      id: '/api/investment-transactions/$id'
      path: '/api/investment-transactions/$id'
      fullPath: '/api/investment-transactions/$id'
      preLoaderRoute: typeof ApiInvestmentTransactionsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/investments/export': {
      id: '/api/investments/export'
      path: '/api/investments/export'
      fullPath: '/api/investments/export'
      preLoaderRoute: typeof ApiInvestmentsExportImport
      parentRoute: typeof rootRoute
    }
    '/api/investments/profitability': {
      id: '/api/investments/profitability'
      path: '/api/investments/profitability'
      fullPath: '/api/investments/profitability'
      preLoaderRoute: typeof ApiInvestmentsProfitabilityImport
      parentRoute: typeof rootRoute
    }
    '/api/invites/accept': {
      id: '/api/invites/accept'
      path: '/api/invites/accept'
      fullPath: '/api/invites/accept'
      preLoaderRoute: typeof ApiInvitesAcceptImport
      parentRoute: typeof rootRoute
    }
    '/api/notifications/$id': {
      id: '/api/notifications/$id'
      path: '/api/notifications/$id'
      fullPath: '/api/notifications/$id'
      preLoaderRoute: typeof ApiNotificationsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/settings/preferences': {
      id: '/api/settings/preferences'
      path: '/api/settings/preferences'
      fullPath: '/api/settings/preferences'
      preLoaderRoute: typeof ApiSettingsPreferencesImport
      parentRoute: typeof rootRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/api/transactions/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/wallets/$id': {
      id: '/api/wallets/$id'
      path: '/api/wallets/$id'
      fullPath: '/api/wallets/$id'
      preLoaderRoute: typeof ApiWalletsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/alerts/': {
      id: '/api/alerts/'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/assets/': {
      id: '/api/assets/'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/budget-copy/': {
      id: '/api/budget-copy/'
      path: '/api/budget-copy'
      fullPath: '/api/budget-copy'
      preLoaderRoute: typeof ApiBudgetCopyIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/budgets/': {
      id: '/api/budgets/'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-card-invoices/': {
      id: '/api/credit-card-invoices/'
      path: '/api/credit-card-invoices'
      fullPath: '/api/credit-card-invoices'
      preLoaderRoute: typeof ApiCreditCardInvoicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-cards/': {
      id: '/api/credit-cards/'
      path: '/api/credit-cards'
      fullPath: '/api/credit-cards'
      preLoaderRoute: typeof ApiCreditCardsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/investment-transactions/': {
      id: '/api/investment-transactions/'
      path: '/api/investment-transactions'
      fullPath: '/api/investment-transactions'
      preLoaderRoute: typeof ApiInvestmentTransactionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/invites/': {
      id: '/api/invites/'
      path: '/api/invites'
      fullPath: '/api/invites'
      preLoaderRoute: typeof ApiInvitesIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/rates/': {
      id: '/api/rates/'
      path: '/api/rates'
      fullPath: '/api/rates'
      preLoaderRoute: typeof ApiRatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/wallets/': {
      id: '/api/wallets/'
      path: '/api/wallets'
      fullPath: '/api/wallets'
      preLoaderRoute: typeof ApiWalletsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/credit-cards': typeof CreditCardsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/api/register': typeof ApiRegisterRoute
  '/invites/accept': typeof InvitesAcceptRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokerage-notes/import': typeof ApiBrokerageNotesImportRoute
  '/api/brokerage-notes/parse': typeof ApiBrokerageNotesParseRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-card-invoices/pay': typeof ApiCreditCardInvoicesPayRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/investment-transactions/$id': typeof ApiInvestmentTransactionsIdRoute
  '/api/investments/export': typeof ApiInvestmentsExportRoute
  '/api/investments/profitability': typeof ApiInvestmentsProfitabilityRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/settings/preferences': typeof ApiSettingsPreferencesRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/assets': typeof ApiAssetsIndexRoute
  '/api/budget-copy': typeof ApiBudgetCopyIndexRoute
  '/api/budgets': typeof ApiBudgetsIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/credit-card-invoices': typeof ApiCreditCardInvoicesIndexRoute
  '/api/credit-cards': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions': typeof ApiInvestmentTransactionsIndexRoute
  '/api/invites': typeof ApiInvitesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/rates': typeof ApiRatesIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/credit-cards': typeof CreditCardsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/api/register': typeof ApiRegisterRoute
  '/invites/accept': typeof InvitesAcceptRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokerage-notes/import': typeof ApiBrokerageNotesImportRoute
  '/api/brokerage-notes/parse': typeof ApiBrokerageNotesParseRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-card-invoices/pay': typeof ApiCreditCardInvoicesPayRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/investment-transactions/$id': typeof ApiInvestmentTransactionsIdRoute
  '/api/investments/export': typeof ApiInvestmentsExportRoute
  '/api/investments/profitability': typeof ApiInvestmentsProfitabilityRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/settings/preferences': typeof ApiSettingsPreferencesRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/assets': typeof ApiAssetsIndexRoute
  '/api/budget-copy': typeof ApiBudgetCopyIndexRoute
  '/api/budgets': typeof ApiBudgetsIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/credit-card-invoices': typeof ApiCreditCardInvoicesIndexRoute
  '/api/credit-cards': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions': typeof ApiInvestmentTransactionsIndexRoute
  '/api/invites': typeof ApiInvitesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/rates': typeof ApiRatesIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/categories': typeof CategoriesRoute
  '/credit-cards': typeof CreditCardsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/api/register': typeof ApiRegisterRoute
  '/invites/accept': typeof InvitesAcceptRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brokerage-notes/import': typeof ApiBrokerageNotesImportRoute
  '/api/brokerage-notes/parse': typeof ApiBrokerageNotesParseRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-card-invoices/pay': typeof ApiCreditCardInvoicesPayRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/investment-transactions/$id': typeof ApiInvestmentTransactionsIdRoute
  '/api/investments/export': typeof ApiInvestmentsExportRoute
  '/api/investments/profitability': typeof ApiInvestmentsProfitabilityRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/notifications/$id': typeof ApiNotificationsIdRoute
  '/api/settings/preferences': typeof ApiSettingsPreferencesRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wallets/$id': typeof ApiWalletsIdRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/assets/': typeof ApiAssetsIndexRoute
  '/api/budget-copy/': typeof ApiBudgetCopyIndexRoute
  '/api/budgets/': typeof ApiBudgetsIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/credit-card-invoices/': typeof ApiCreditCardInvoicesIndexRoute
  '/api/credit-cards/': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions/': typeof ApiInvestmentTransactionsIndexRoute
  '/api/invites/': typeof ApiInvitesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/rates/': typeof ApiRatesIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/api/wallets/': typeof ApiWalletsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/categories'
    | '/credit-cards'
    | '/goals'
    | '/investments'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/api/register'
    | '/invites/accept'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/brokerage-notes/import'
    | '/api/brokerage-notes/parse'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-card-invoices/pay'
    | '/api/credit-cards/$id'
    | '/api/investment-transactions/$id'
    | '/api/investments/export'
    | '/api/investments/profitability'
    | '/api/invites/accept'
    | '/api/notifications/$id'
    | '/api/settings/preferences'
    | '/api/transactions/$id'
    | '/api/wallets/$id'
    | '/api/alerts'
    | '/api/assets'
    | '/api/budget-copy'
    | '/api/budgets'
    | '/api/categories'
    | '/api/credit-card-invoices'
    | '/api/credit-cards'
    | '/api/investment-transactions'
    | '/api/invites'
    | '/api/notifications'
    | '/api/rates'
    | '/api/transactions'
    | '/api/wallets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/categories'
    | '/credit-cards'
    | '/goals'
    | '/investments'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/api/register'
    | '/invites/accept'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/brokerage-notes/import'
    | '/api/brokerage-notes/parse'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-card-invoices/pay'
    | '/api/credit-cards/$id'
    | '/api/investment-transactions/$id'
    | '/api/investments/export'
    | '/api/investments/profitability'
    | '/api/invites/accept'
    | '/api/notifications/$id'
    | '/api/settings/preferences'
    | '/api/transactions/$id'
    | '/api/wallets/$id'
    | '/api/alerts'
    | '/api/assets'
    | '/api/budget-copy'
    | '/api/budgets'
    | '/api/categories'
    | '/api/credit-card-invoices'
    | '/api/credit-cards'
    | '/api/investment-transactions'
    | '/api/invites'
    | '/api/notifications'
    | '/api/rates'
    | '/api/transactions'
    | '/api/wallets'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/categories'
    | '/credit-cards'
    | '/goals'
    | '/investments'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/api/register'
    | '/invites/accept'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/brokerage-notes/import'
    | '/api/brokerage-notes/parse'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-card-invoices/pay'
    | '/api/credit-cards/$id'
    | '/api/investment-transactions/$id'
    | '/api/investments/export'
    | '/api/investments/profitability'
    | '/api/invites/accept'
    | '/api/notifications/$id'
    | '/api/settings/preferences'
    | '/api/transactions/$id'
    | '/api/wallets/$id'
    | '/api/alerts/'
    | '/api/assets/'
    | '/api/budget-copy/'
    | '/api/budgets/'
    | '/api/categories/'
    | '/api/credit-card-invoices/'
    | '/api/credit-cards/'
    | '/api/investment-transactions/'
    | '/api/invites/'
    | '/api/notifications/'
    | '/api/rates/'
    | '/api/transactions/'
    | '/api/wallets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  CategoriesRoute: typeof CategoriesRoute
  CreditCardsRoute: typeof CreditCardsRoute
  GoalsRoute: typeof GoalsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletsRoute: typeof WalletsRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  InvitesAcceptRoute: typeof InvitesAcceptRoute
  ApiAlertsIdRoute: typeof ApiAlertsIdRoute
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBrokerageNotesImportRoute: typeof ApiBrokerageNotesImportRoute
  ApiBrokerageNotesParseRoute: typeof ApiBrokerageNotesParseRoute
  ApiBudgetsIdRoute: typeof ApiBudgetsIdRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiCreditCardInvoicesPayRoute: typeof ApiCreditCardInvoicesPayRoute
  ApiCreditCardsIdRoute: typeof ApiCreditCardsIdRoute
  ApiInvestmentTransactionsIdRoute: typeof ApiInvestmentTransactionsIdRoute
  ApiInvestmentsExportRoute: typeof ApiInvestmentsExportRoute
  ApiInvestmentsProfitabilityRoute: typeof ApiInvestmentsProfitabilityRoute
  ApiInvitesAcceptRoute: typeof ApiInvitesAcceptRoute
  ApiNotificationsIdRoute: typeof ApiNotificationsIdRoute
  ApiSettingsPreferencesRoute: typeof ApiSettingsPreferencesRoute
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
  ApiWalletsIdRoute: typeof ApiWalletsIdRoute
  ApiAlertsIndexRoute: typeof ApiAlertsIndexRoute
  ApiAssetsIndexRoute: typeof ApiAssetsIndexRoute
  ApiBudgetCopyIndexRoute: typeof ApiBudgetCopyIndexRoute
  ApiBudgetsIndexRoute: typeof ApiBudgetsIndexRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiCreditCardInvoicesIndexRoute: typeof ApiCreditCardInvoicesIndexRoute
  ApiCreditCardsIndexRoute: typeof ApiCreditCardsIndexRoute
  ApiInvestmentTransactionsIndexRoute: typeof ApiInvestmentTransactionsIndexRoute
  ApiInvitesIndexRoute: typeof ApiInvitesIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiRatesIndexRoute: typeof ApiRatesIndexRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
  ApiWalletsIndexRoute: typeof ApiWalletsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  CategoriesRoute: CategoriesRoute,
  CreditCardsRoute: CreditCardsRoute,
  GoalsRoute: GoalsRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  WalletsRoute: WalletsRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  InvitesAcceptRoute: InvitesAcceptRoute,
  ApiAlertsIdRoute: ApiAlertsIdRoute,
  ApiAssetsIdRoute: ApiAssetsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBrokerageNotesImportRoute: ApiBrokerageNotesImportRoute,
  ApiBrokerageNotesParseRoute: ApiBrokerageNotesParseRoute,
  ApiBudgetsIdRoute: ApiBudgetsIdRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiCreditCardInvoicesPayRoute: ApiCreditCardInvoicesPayRoute,
  ApiCreditCardsIdRoute: ApiCreditCardsIdRoute,
  ApiInvestmentTransactionsIdRoute: ApiInvestmentTransactionsIdRoute,
  ApiInvestmentsExportRoute: ApiInvestmentsExportRoute,
  ApiInvestmentsProfitabilityRoute: ApiInvestmentsProfitabilityRoute,
  ApiInvitesAcceptRoute: ApiInvitesAcceptRoute,
  ApiNotificationsIdRoute: ApiNotificationsIdRoute,
  ApiSettingsPreferencesRoute: ApiSettingsPreferencesRoute,
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
  ApiWalletsIdRoute: ApiWalletsIdRoute,
  ApiAlertsIndexRoute: ApiAlertsIndexRoute,
  ApiAssetsIndexRoute: ApiAssetsIndexRoute,
  ApiBudgetCopyIndexRoute: ApiBudgetCopyIndexRoute,
  ApiBudgetsIndexRoute: ApiBudgetsIndexRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiCreditCardInvoicesIndexRoute: ApiCreditCardInvoicesIndexRoute,
  ApiCreditCardsIndexRoute: ApiCreditCardsIndexRoute,
  ApiInvestmentTransactionsIndexRoute: ApiInvestmentTransactionsIndexRoute,
  ApiInvitesIndexRoute: ApiInvitesIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiRatesIndexRoute: ApiRatesIndexRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
  ApiWalletsIndexRoute: ApiWalletsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/budget",
        "/categories",
        "/credit-cards",
        "/goals",
        "/investments",
        "/login",
        "/register",
        "/reports",
        "/settings",
        "/transactions",
        "/wallets",
        "/api/register",
        "/invites/accept",
        "/api/alerts/$id",
        "/api/assets/$id",
        "/api/auth/$",
        "/api/brokerage-notes/import",
        "/api/brokerage-notes/parse",
        "/api/budgets/$id",
        "/api/categories/$id",
        "/api/credit-card-invoices/pay",
        "/api/credit-cards/$id",
        "/api/investment-transactions/$id",
        "/api/investments/export",
        "/api/investments/profitability",
        "/api/invites/accept",
        "/api/notifications/$id",
        "/api/settings/preferences",
        "/api/transactions/$id",
        "/api/wallets/$id",
        "/api/alerts/",
        "/api/assets/",
        "/api/budget-copy/",
        "/api/budgets/",
        "/api/categories/",
        "/api/credit-card-invoices/",
        "/api/credit-cards/",
        "/api/investment-transactions/",
        "/api/invites/",
        "/api/notifications/",
        "/api/rates/",
        "/api/transactions/",
        "/api/wallets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/budget": {
      "filePath": "budget.tsx"
    },
    "/categories": {
      "filePath": "categories.tsx"
    },
    "/credit-cards": {
      "filePath": "credit-cards.tsx"
    },
    "/goals": {
      "filePath": "goals.tsx"
    },
    "/investments": {
      "filePath": "investments.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/reports": {
      "filePath": "reports.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/transactions": {
      "filePath": "transactions.tsx"
    },
    "/wallets": {
      "filePath": "wallets.tsx"
    },
    "/api/register": {
      "filePath": "api/register.ts"
    },
    "/invites/accept": {
      "filePath": "invites.accept.tsx"
    },
    "/api/alerts/$id": {
      "filePath": "api/alerts/$id.ts"
    },
    "/api/assets/$id": {
      "filePath": "api/assets/$id.ts"
    },
    "/api/auth/$": {
      "filePath": "api/auth/$.tsx"
    },
    "/api/brokerage-notes/import": {
      "filePath": "api/brokerage-notes/import.ts"
    },
    "/api/brokerage-notes/parse": {
      "filePath": "api/brokerage-notes/parse.ts"
    },
    "/api/budgets/$id": {
      "filePath": "api/budgets/$id.ts"
    },
    "/api/categories/$id": {
      "filePath": "api/categories/$id.ts"
    },
    "/api/credit-card-invoices/pay": {
      "filePath": "api/credit-card-invoices/pay.ts"
    },
    "/api/credit-cards/$id": {
      "filePath": "api/credit-cards/$id.ts"
    },
    "/api/investment-transactions/$id": {
      "filePath": "api/investment-transactions/$id.ts"
    },
    "/api/investments/export": {
      "filePath": "api/investments/export.ts"
    },
    "/api/investments/profitability": {
      "filePath": "api/investments/profitability.ts"
    },
    "/api/invites/accept": {
      "filePath": "api/invites/accept.ts"
    },
    "/api/notifications/$id": {
      "filePath": "api/notifications/$id.ts"
    },
    "/api/settings/preferences": {
      "filePath": "api/settings/preferences.ts"
    },
    "/api/transactions/$id": {
      "filePath": "api/transactions/$id.ts"
    },
    "/api/wallets/$id": {
      "filePath": "api/wallets/$id.ts"
    },
    "/api/alerts/": {
      "filePath": "api/alerts/index.ts"
    },
    "/api/assets/": {
      "filePath": "api/assets/index.ts"
    },
    "/api/budget-copy/": {
      "filePath": "api/budget-copy/index.ts"
    },
    "/api/budgets/": {
      "filePath": "api/budgets/index.ts"
    },
    "/api/categories/": {
      "filePath": "api/categories/index.ts"
    },
    "/api/credit-card-invoices/": {
      "filePath": "api/credit-card-invoices/index.ts"
    },
    "/api/credit-cards/": {
      "filePath": "api/credit-cards/index.ts"
    },
    "/api/investment-transactions/": {
      "filePath": "api/investment-transactions/index.ts"
    },
    "/api/invites/": {
      "filePath": "api/invites/index.ts"
    },
    "/api/notifications/": {
      "filePath": "api/notifications/index.ts"
    },
    "/api/rates/": {
      "filePath": "api/rates/index.ts"
    },
    "/api/transactions/": {
      "filePath": "api/transactions/index.ts"
    },
    "/api/wallets/": {
      "filePath": "api/wallets/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
