/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as ApiTransactionsIndexImport } from './routes/api/transactions/index'
import { Route as ApiInvestmentTransactionsIndexImport } from './routes/api/investment-transactions/index'
import { Route as ApiCreditCardsIndexImport } from './routes/api/credit-cards/index'
import { Route as ApiCategoriesIndexImport } from './routes/api/categories/index'
import { Route as ApiBudgetsIndexImport } from './routes/api/budgets/index'
import { Route as ApiAssetsIndexImport } from './routes/api/assets/index'
import { Route as ApiAlertsIndexImport } from './routes/api/alerts/index'
import { Route as ApiTransactionsIdImport } from './routes/api/transactions/$id'
import { Route as ApiCreditCardsIdImport } from './routes/api/credit-cards/$id'
import { Route as ApiCategoriesIdImport } from './routes/api/categories/$id'
import { Route as ApiBudgetsIdImport } from './routes/api/budgets/$id'
import { Route as ApiAuthSplatImport } from './routes/api/auth/$'
import { Route as ApiAssetsIdImport } from './routes/api/assets/$id'
import { Route as ApiAlertsIdImport } from './routes/api/alerts/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ApiTransactionsIndexRoute = ApiTransactionsIndexImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const ApiInvestmentTransactionsIndexRoute =
  ApiInvestmentTransactionsIndexImport.update({
    id: '/api/investment-transactions/',
    path: '/api/investment-transactions/',
    getParentRoute: () => rootRoute,
  } as any)

const ApiCreditCardsIndexRoute = ApiCreditCardsIndexImport.update({
  id: '/api/credit-cards/',
  path: '/api/credit-cards/',
  getParentRoute: () => rootRoute,
} as any)

const ApiCategoriesIndexRoute = ApiCategoriesIndexImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRoute,
} as any)

const ApiBudgetsIndexRoute = ApiBudgetsIndexImport.update({
  id: '/api/budgets/',
  path: '/api/budgets/',
  getParentRoute: () => rootRoute,
} as any)

const ApiAssetsIndexRoute = ApiAssetsIndexImport.update({
  id: '/api/assets/',
  path: '/api/assets/',
  getParentRoute: () => rootRoute,
} as any)

const ApiAlertsIndexRoute = ApiAlertsIndexImport.update({
  id: '/api/alerts/',
  path: '/api/alerts/',
  getParentRoute: () => rootRoute,
} as any)

const ApiTransactionsIdRoute = ApiTransactionsIdImport.update({
  id: '/api/transactions/$id',
  path: '/api/transactions/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiCreditCardsIdRoute = ApiCreditCardsIdImport.update({
  id: '/api/credit-cards/$id',
  path: '/api/credit-cards/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiCategoriesIdRoute = ApiCategoriesIdImport.update({
  id: '/api/categories/$id',
  path: '/api/categories/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiBudgetsIdRoute = ApiBudgetsIdImport.update({
  id: '/api/budgets/$id',
  path: '/api/budgets/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiAuthSplatRoute = ApiAuthSplatImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRoute,
} as any)

const ApiAssetsIdRoute = ApiAssetsIdImport.update({
  id: '/api/assets/$id',
  path: '/api/assets/$id',
  getParentRoute: () => rootRoute,
} as any)

const ApiAlertsIdRoute = ApiAlertsIdImport.update({
  id: '/api/alerts/$id',
  path: '/api/alerts/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/api/alerts/$id': {
      id: '/api/alerts/$id'
      path: '/api/alerts/$id'
      fullPath: '/api/alerts/$id'
      preLoaderRoute: typeof ApiAlertsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/api/assets/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatImport
      parentRoute: typeof rootRoute
    }
    '/api/budgets/$id': {
      id: '/api/budgets/$id'
      path: '/api/budgets/$id'
      fullPath: '/api/budgets/$id'
      preLoaderRoute: typeof ApiBudgetsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/api/categories/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-cards/$id': {
      id: '/api/credit-cards/$id'
      path: '/api/credit-cards/$id'
      fullPath: '/api/credit-cards/$id'
      preLoaderRoute: typeof ApiCreditCardsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/api/transactions/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdImport
      parentRoute: typeof rootRoute
    }
    '/api/alerts/': {
      id: '/api/alerts/'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/assets/': {
      id: '/api/assets/'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/budgets/': {
      id: '/api/budgets/'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/credit-cards/': {
      id: '/api/credit-cards/'
      path: '/api/credit-cards'
      fullPath: '/api/credit-cards'
      preLoaderRoute: typeof ApiCreditCardsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/investment-transactions/': {
      id: '/api/investment-transactions/'
      path: '/api/investment-transactions'
      fullPath: '/api/investment-transactions'
      preLoaderRoute: typeof ApiInvestmentTransactionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/assets': typeof ApiAssetsIndexRoute
  '/api/budgets': typeof ApiBudgetsIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/credit-cards': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions': typeof ApiInvestmentTransactionsIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/assets': typeof ApiAssetsIndexRoute
  '/api/budgets': typeof ApiBudgetsIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/credit-cards': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions': typeof ApiInvestmentTransactionsIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts/$id': typeof ApiAlertsIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/budgets/$id': typeof ApiBudgetsIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/credit-cards/$id': typeof ApiCreditCardsIdRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/assets/': typeof ApiAssetsIndexRoute
  '/api/budgets/': typeof ApiBudgetsIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/credit-cards/': typeof ApiCreditCardsIndexRoute
  '/api/investment-transactions/': typeof ApiInvestmentTransactionsIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-cards/$id'
    | '/api/transactions/$id'
    | '/api/alerts'
    | '/api/assets'
    | '/api/budgets'
    | '/api/categories'
    | '/api/credit-cards'
    | '/api/investment-transactions'
    | '/api/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-cards/$id'
    | '/api/transactions/$id'
    | '/api/alerts'
    | '/api/assets'
    | '/api/budgets'
    | '/api/categories'
    | '/api/credit-cards'
    | '/api/investment-transactions'
    | '/api/transactions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/alerts/$id'
    | '/api/assets/$id'
    | '/api/auth/$'
    | '/api/budgets/$id'
    | '/api/categories/$id'
    | '/api/credit-cards/$id'
    | '/api/transactions/$id'
    | '/api/alerts/'
    | '/api/assets/'
    | '/api/budgets/'
    | '/api/categories/'
    | '/api/credit-cards/'
    | '/api/investment-transactions/'
    | '/api/transactions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAlertsIdRoute: typeof ApiAlertsIdRoute
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBudgetsIdRoute: typeof ApiBudgetsIdRoute
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
  ApiCreditCardsIdRoute: typeof ApiCreditCardsIdRoute
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
  ApiAlertsIndexRoute: typeof ApiAlertsIndexRoute
  ApiAssetsIndexRoute: typeof ApiAssetsIndexRoute
  ApiBudgetsIndexRoute: typeof ApiBudgetsIndexRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiCreditCardsIndexRoute: typeof ApiCreditCardsIndexRoute
  ApiInvestmentTransactionsIndexRoute: typeof ApiInvestmentTransactionsIndexRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAlertsIdRoute: ApiAlertsIdRoute,
  ApiAssetsIdRoute: ApiAssetsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBudgetsIdRoute: ApiBudgetsIdRoute,
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
  ApiCreditCardsIdRoute: ApiCreditCardsIdRoute,
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
  ApiAlertsIndexRoute: ApiAlertsIndexRoute,
  ApiAssetsIndexRoute: ApiAssetsIndexRoute,
  ApiBudgetsIndexRoute: ApiBudgetsIndexRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiCreditCardsIndexRoute: ApiCreditCardsIndexRoute,
  ApiInvestmentTransactionsIndexRoute: ApiInvestmentTransactionsIndexRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/api/alerts/$id",
        "/api/assets/$id",
        "/api/auth/$",
        "/api/budgets/$id",
        "/api/categories/$id",
        "/api/credit-cards/$id",
        "/api/transactions/$id",
        "/api/alerts/",
        "/api/assets/",
        "/api/budgets/",
        "/api/categories/",
        "/api/credit-cards/",
        "/api/investment-transactions/",
        "/api/transactions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/api/alerts/$id": {
      "filePath": "api/alerts/$id.ts"
    },
    "/api/assets/$id": {
      "filePath": "api/assets/$id.ts"
    },
    "/api/auth/$": {
      "filePath": "api/auth/$.tsx"
    },
    "/api/budgets/$id": {
      "filePath": "api/budgets/$id.ts"
    },
    "/api/categories/$id": {
      "filePath": "api/categories/$id.ts"
    },
    "/api/credit-cards/$id": {
      "filePath": "api/credit-cards/$id.ts"
    },
    "/api/transactions/$id": {
      "filePath": "api/transactions/$id.ts"
    },
    "/api/alerts/": {
      "filePath": "api/alerts/index.ts"
    },
    "/api/assets/": {
      "filePath": "api/assets/index.ts"
    },
    "/api/budgets/": {
      "filePath": "api/budgets/index.ts"
    },
    "/api/categories/": {
      "filePath": "api/categories/index.ts"
    },
    "/api/credit-cards/": {
      "filePath": "api/credit-cards/index.ts"
    },
    "/api/investment-transactions/": {
      "filePath": "api/investment-transactions/index.ts"
    },
    "/api/transactions/": {
      "filePath": "api/transactions/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
